name: Generate Partition

description: Generates a JSON object defining an ArmoniK partition.

inputs:
  partition_name:
    description: 'Name of the partition'
    required: true
    default: 'helloworld'

  worker_image:
    description: 'Docker image for the worker'
    required: true
    default: 'dockerhubaneo/armonik_demo_helloworld_worker'
    
  worker_tag:
    description: 'Tag for the worker image'
    required: true
    default: 'latest'

  socket_type:
    description: 'Socket type'
    required: false
    default: 'unixdomainsocket'

runs:
  using: "composite"
  steps:
    - name: Generate Partition JSON
      id: generate_partition
      shell: bash
      run: |
        json_output=$(jq -n \
          --arg partition_name "${{ inputs.partition_name }}" \
          --arg socket_type "${{ inputs.socket_type }}" \
          --arg worker_image "${{ inputs.worker_image }}" \
          --arg worker_tag "${{ inputs.worker_tag }}" \
          '.compute_plane={
            ($partition_name): {
              replicas: 0,
              socket_type: $socket_type,
              polling_agent: {
                limits: { cpu: "2000m", memory: "2048Mi" },
                requests: { cpu: "50m", memory: "50Mi" }
              },
              worker: [{
                image: $worker_image,
                tag: $worker_tag,
                limits: { cpu: "1000m", memory: "1024Mi" },
                requests: { cpu: "50m", memory: "50Mi" }
              }],
              hpa: {
                type: "prometheus",
                polling_interval: 15,
                cooldown_period: 300,
                min_replica_count: 0,
                max_replica_count: 5,
                behavior: {
                  restore_to_original_replica_count: true,
                  stabilization_window_seconds: 300,
                  type: "Percent",
                  value: 100,
                  period_seconds: 15
                },
                triggers: [{ type: "prometheus", threshold: 2 }]
              }
            }
          }')
        json_output=$(echo "$json_output" | jq -c .)
        echo "PARTITION_JSON=$json_output" >> $GITHUB_ENV

    - name: Output Partition JSON
      shell: bash
      run: echo "${{ env.PARTITION_JSON }}"
