name: DeployTest

on:
  push:

jobs:
  versionning:
    name: Versionning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Generate Version
      id: genver
      uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832 # 2.8.0
      with:
        minor-identifier: "feat:"
        release-branch: release
        dev-branch: main
        prefix: v

    - name: Print version
      run: echo VERSION ${{ steps.genver.outputs.version }} >> $GITHUB_STEP_SUMMARY

  formatCsharp:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        solution:
          - AllSamples.sln
          - csharp/native/Demo.sln
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4
      with:
        dotnet-version: 8.x

    - name: Install ReSharper
      run: |
        dotnet tool install -g JetBrains.ReSharper.GlobalTools --version 2025.1.2

    - name: Restore
      run: |
        dotnet restore ${{ matrix.solution }}

    - name: Reformat
      run: |
        jb cleanupcode ${{ matrix.solution }}

    - name: Check Diff
      id: check-diff
      run: |
        DIFF="$(git diff --name-only)"

        if [ -z "$DIFF" ]; then
          echo "OK: Format is clean"
        else
          echo "Error: Format was not clean"
          echo "List of files:"
          echo "$DIFF"
          git diff
          exit 1
        fi
    - name: Generate patch
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      run: |
        git diff > patch-csharp.diff
        
    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      with:
        name: patch-csharp
        path: ./patch-csharp.diff
        
  buildProjects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4
      with:
        dotnet-version: 8.x

    - name: Build the package
      run: |
        dotnet build AllSamples.sln

  setupDemoNames:
    runs-on: ubuntu-latest
    outputs:
      csharp-demo-names: ${{ steps.set-csharp-demos.outputs.csharp-demo-names }}
      csharp-demo-dirs: ${{ steps.set-csharp-demos.outputs.csharp-demo-dirs }}
      cpp-demo-names: ${{ steps.set-cpp-demos.outputs.cpp-demo-names }}
      cpp-demo-dirs: ${{ steps.set-cpp-demos.outputs.cpp-demo-dirs }}
    steps:
      - name: CSharp demos
        id: set-csharp-demos
        run: |
          CSHARP_DEMO_DIRS='["HelloWorld","MultipleResults","SubTasking","LinearSubTasking","DynamicSubmission"]'
          CSHARP_DEMO_NAMES=$(echo "${CSHARP_DEMO_DIRS}" | jq -c 'map(ascii_downcase)')
          echo "csharp-demo-dirs=${CSHARP_DEMO_DIRS}" >> $GITHUB_OUTPUT
          echo "csharp-demo-names=${CSHARP_DEMO_NAMES}" >> $GITHUB_OUTPUT

      - name: Cpp demos
        id: set-cpp-demos
        run: |
          CPP_DEMO_DIRS='["HelloWorldAPI","HelloWorldSDK"]'
          CPP_DEMO_NAMES=$(echo "${CPP_DEMO_DIRS}" | jq -c 'map(ascii_downcase)')
          echo "cpp-demo-dirs=${CPP_DEMO_DIRS}" >> $GITHUB_OUTPUT
          echo "cpp-demo-names=${CPP_DEMO_NAMES}" >> $GITHUB_OUTPUT

  buildCSharpImages:
    runs-on: ubuntu-latest
    needs:
      - versionning
      - buildProjects
      - setupDemoNames
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    strategy:
      fail-fast: true
      matrix:
        demodir: ${{ fromJson(needs.setupDemoNames.outputs.csharp-demo-dirs) }}
        role: [Client, Worker]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="dockerhubaneo/armonik_demo_$(echo '${{ matrix.demodir }}' | tr '[:upper:]' '[:lower:]')_$(echo '${{ matrix.role }}' | tr '[:upper:]' '[:lower:]')"
          docker build \
            -t ${IMAGE_NAME}:${VERSION} \
            -f ./csharp/native/${{ matrix.demodir }}/${{ matrix.role }}/Dockerfile \
            csharp/native/
          docker push ${IMAGE_NAME}:${VERSION}

  buildCppImages:
    runs-on: ubuntu-latest
    needs:
      - versionning
      - setupDemoNames
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    strategy:
      fail-fast: true
      matrix:
        demodir: ${{ fromJson(needs.setupDemoNames.outputs.cpp-demo-dirs) }}
        role: [client, worker]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - name: Build and push Docker image
        run: |
          API_VERSION=$(curl -fsS https://raw.githubusercontent.com/aneoconsulting/ArmoniK/main/versions.tfvars.json | jq -r '.armonik_versions.api')
          SDK_VERSION=$(curl -fsS https://raw.githubusercontent.com/aneoconsulting/ArmoniK/main/versions.tfvars.json | jq -r '.armonik_versions.extcpp')
          IMAGE_NAME="dockerhubaneo/armonik_demo_cpp_$(echo '${{ matrix.demodir }}' | tr '[:upper:]' '[:lower:]')_${{ matrix.role }}"
          docker build \
            -t ${IMAGE_NAME}:${VERSION} \
            -f ./cpp/${{ matrix.demodir }}/${{ matrix.role }}/Dockerfile \
            --build-arg="API_VERSION=${API_VERSION}" \
            --build-arg="SDK_VERSION=${SDK_VERSION}" \
            cpp/${{ matrix.demodir }}/${{ matrix.role }}/
          docker push ${IMAGE_NAME}:${VERSION}

  CSharpSamples:
    runs-on: ubuntu-latest
    needs:
      - versionning
      - buildCSharpImages
    strategy:
      fail-fast: false
      matrix:
        demo: ${{ fromJson(needs.setupDemoNames.outputs.csharp-demos) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}
      - name: Install Dependencies
        uses: aneoconsulting/ArmoniK.Action.Deploy/dependencies@main
        with:
            docker: true
            terraform: true
            k3s: true
            aws: true

      - name: Checkout Infra
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
            repository: aneoconsulting/ArmoniK
            path: infra

      - name: Change version
        run: |
          cp tools/parameters.tfvars \
            ${{ github.workspace }}/infra/infrastructure/quick-deploy/localhost/all-in-one/parameters.tfvars

          cat ${{ github.workspace }}/infra/versions.tfvars.json \
            | jq --arg version "${{ needs.versionning.outputs.version }}" '
              .armonik_versions.samples = $version
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_helloworld_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_multipleresults_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_subtasking_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_linearsubtasking_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_dynamicsubmission_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_cpp_helloworldapi_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_cpp_helloworldsdk_worker"]
            ' > .versions.tfvars.json

          mv .versions.tfvars.json \
            ${{ github.workspace }}/infra/versions.tfvars.json
    
      - id: deploy
        name: Deploy
        uses: aneoconsulting/ArmoniK.Action.Deploy/deploy@main
        with:
          working-directory: ${{ github.workspace }}/infra
          type: localhost
          log-suffix: ${{ matrix.demo }}
         
      - name: Run Demo Client
        timeout-minutes: 10
        run: |
         export CPIP=$(kubectl get svc control-plane -n armonik -o custom-columns="IP:.spec.clusterIP" --no-headers=true)
         export CPPort=$(kubectl get svc control-plane -n armonik -o custom-columns="PORT:.spec.ports[*].port" --no-headers=true)
         export Grpc__Endpoint=http://$CPIP:$CPPort
         docker run --rm dockerhubaneo/armonik_demo_${{ matrix.demo }}_client:${{ needs.versionning.outputs.version }} --endpoint $Grpc__Endpoint --partition ${{ matrix.demo }}

  testInfraWorker:
    needs:
      - versionning
      - buildProjects
    strategy:
      matrix:
        scenario:
           - --nbTask 224  --nbInputBytes 4029815 --nbOutputBytes 226016  --workLoadTimeInMs 10

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      ARMONIK_SHARED_HOST_PATH: ${{ github.workspace }}/infra/infrastructure/quick-deploy/localhost/all-in-one/data/
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        uses: aneoconsulting/ArmoniK.Action.Deploy/dependencies@main
        with:
          docker: true
          terraform: true
          k3s: true
          aws: true

      - name: Checkout Infra
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: aneoconsulting/ArmoniK
          path: infra

      - name: Change version
        run: |
          cp tools/parameters.tfvars \
            ${{ github.workspace }}/infra/infrastructure/quick-deploy/localhost/all-in-one/parameters.tfvars

          cat ${{ github.workspace }}/infra/versions.tfvars.json \
            | jq --arg version "${{ needs.versionning.outputs.version }}" '
              .armonik_versions.samples = $version
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_helloworld_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_multipleresults_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_subtasking_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_linearsubtasking_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_dynamicsubmission_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_cpp_helloworldapi_worker"]
              | .armonik_images.samples += ["dockerhubaneo/armonik_demo_cpp_helloworldsdk_worker"]
            ' > .versions.tfvars.json

          mv .versions.tfvars.json \
            ${{ github.workspace }}/infra/versions.tfvars.json

      - id: deploy
        name: Deploy
        uses: aneoconsulting/ArmoniK.Action.Deploy/deploy@main
        with:
          working-directory: ${{ github.workspace }}/infra
          type: localhost
          shared-data-folder: ${{ env.ARMONIK_SHARED_HOST_PATH }}
          log-suffix: infraWorker

      - name: Run UnifiedAPI
        timeout-minutes: 15
        run: |
         cd tools/tests
         bash -x ./unified_api.sh

      - name: Run StressTests
        timeout-minutes: 15
        run: |
         cd tools/tests
         bash -x ./stress-tests.sh -- stressTest ${{ matrix.scenario }}
      - name: Copy logs
        if: always()
        shell: bash
        run: |
          set -e
          mkdir -p /tmp/armoniklogs
          sudo find /var/log/pods/ -maxdepth 1 -iname 'armonik_*' -exec cp -rL '{}' /tmp/armoniklogs/ ';'
          sudo chown $USER -R /tmp/armoniklogs
          find /tmp/armoniklogs -name "*.log"

      - name: Store logs
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: always()
        with:
          name: Logs Worker
          path: /tmp/armoniklogs/**/*.log
          retention-days: 5
          
      - name: Destroy deployment
        if: success() || failure()
        uses: aneoconsulting/ArmoniK.Action.Deploy/destroy@main
        with:
          working-directory: ${{ github.workspace }}/infra
          type: localhost
